// In vijf zinnen — données des 24 contextes (8 par niveau A1 · A2 · B1)
// crit : 5 critères (une phrase chacun) · k = étiquette courte
// ex : la production modèle ; {n:texte} ou {n:texte|étiquette} = bribe encadrée, reliée au critère n
// mode : 'W' production écrite · 'O' production orale
// scene : décor en coordonnées relatives (fx, fy, fw, fh entre 0 et 1 ; taille des emoji relative à la hauteur)
//   ['bg', 'out' | 'in', haut, bas, horizon] · ['r', fx, fy, fw, fh, couleur, arrondi] · ['sign', texte, fx, fy, fw, fh, couleur]
//   ['win', fx, fy, fw, fh] · ['e', emoji, fx, fy, taille] · ['line', fx1, fy1, fx2, fy2, couleur]

const LEVELS = [
  {
    id: 'A1', name: 'A1 · Découverte', color: 'accent3',
    spec: ['**zijn / hebben** · présent (-t)', 'ordre des mots et **inversion**', '**er is / er zijn**', '**niet / geen**', '**pluriel** · possessifs', 'prépositions de lieu', 'adjectif **qualificatif / attribut**', '**gaan** + infinitif · verbes à particule', '**en · maar · want**'],
    ctx: [
      {
        t: 'Op het terras', fr: 'En terrasse', mode: 'O',
        sit: 'Il fait beau. Vous êtes en terrasse avec un·e collègue. Décrivez la scène et commandez.',
        scene: [['bg', 'out', 'D6ECFA', 'E9DFCF', 0.66], ['e', 'sun', 0.82, 0.04, 0.17], ['sign', 'CAFÉ', 0.04, 0.06, 0.24, 0.13, 'tx2'], ['e', 'umbrella-on-ground', 0.28, 0.02, 0.6],
          ['r', 0.3, 0.62, 0.4, 0.035, '8A96A8', 0.01], ['r', 0.485, 0.655, 0.03, 0.22, '8A96A8', 0], ['e', 'hot-beverage', 0.36, 0.49, 0.13], ['e', 'waffle', 0.52, 0.5, 0.12], ['e', 'woman', 0.02, 0.42, 0.4], ['e', 'man', 0.69, 0.42, 0.4]],
        crit: [
          { t: 'Situez la scène avec le verbe **ZIJN** : où êtes-vous ? avec qui ?', k: 'ZIJN' },
          { t: 'Commandez une boisson et un snack avec **IK WIL GRAAG…**', k: 'IK WIL GRAAG' },
          { t: 'Décrivez le temps avec **HET IS** + un adjectif.', k: 'HET IS + adj.' },
          { t: 'Donnez le prix avec **KOST / KOSTEN** + un nombre.', k: 'KOSTEN + prix' },
          { t: 'Terminez par une chute avec **MAAR** et **GEEN**.', k: 'MAAR … GEEN' },
        ],
        ex: [
          'Ik {1:ben} op een terras in Brussel, met mijn collega Sofie.',
          'Ik {2:wil graag} een koffie en een wafel, alstublieft.',
          '{3:Het is warm} en zonnig vandaag.',
          'De koffie en de wafel {4:kosten|KOSTEN} samen {4:acht euro|prix}.',
          '{5:Maar|MAAR} ik heb {5:geen|GEEN} geld bij me!',
        ],
        notes: 'Par deux : A décrit la scène et commande, B joue le serveur ou la serveuse (« Wat mag het zijn? »). Acceptez aussi « Ik neem… » pour la commande. « alstublieft » (vous) / « alsjeblieft » (tu). Pluriel du verbe : de koffie en de wafel kostEN.',
      },
      {
        t: 'Op de markt', fr: 'Au marché', mode: 'W',
        sit: 'Samedi matin, vous faites vos courses au marché. Racontez.',
        scene: [['bg', 'out', 'D6ECFA', 'E9DFCF', 0.7], ['r', 0.04, 0.05, 0.92, 0.14, 'accent6', 0.03], ['sign', 'MARKT', 0.34, 0.06, 0.32, 0.12, 'accent6'], ['e', 'man-farmer', 0.38, 0.17, 0.36],
          ['r', 0.04, 0.52, 0.92, 0.2, 'B8865B', 0.02], ['e', 'red-apple', 0.07, 0.37, 0.15], ['e', 'tomato', 0.2, 0.37, 0.15], ['e', 'banana', 0.62, 0.37, 0.15], ['e', 'strawberry', 0.75, 0.37, 0.15], ['e', 'carrot', 0.86, 0.37, 0.14],
          ['e', 'basket', 0.76, 0.73, 0.24], ['e', 'euro-banknote', 0.06, 0.76, 0.18]],
        crit: [
          { t: 'Commencez par le jour : **OP ZATERDAG** + verbe + sujet (inversion).', k: 'INVERSION' },
          { t: 'Nommez trois fruits ou légumes au **pluriel** (-S / -EN).', k: 'PLURIEL' },
          { t: 'Décrivez le marché avec **ER IS** et / ou **ER ZIJN**.', k: 'ER IS / ER ZIJN' },
          { t: 'Posez une question au marchand avec **HOEVEEL**.', k: 'HOEVEEL' },
          { t: 'Terminez par une chute avec **NIET** ou **GEEN**.', k: 'NIET / GEEN' },
        ],
        ex: [
          '{1:Op zaterdag ben ik} op de markt in Gent.',
          'Ik koop {2:appels|-S}, {2:tomaten|-EN} en drie {2:bananen|-EN}.',
          '{3:Er zijn|ER ZIJN} veel mensen en {3:er is|ER IS} muziek.',
          '“{4:Hoeveel} kosten de aardbeien, meneer?”',
          'Oei, ik heb {5:geen} tas bij me!',
        ],
        notes: 'Vérifiez l’inversion : ✗ « Op zaterdag ik ben… ». Pluriel en -s après -el, -em, -en, -er et certaines voyelles (appels) ; en -en ailleurs (tomaten, bananen). « er is » + singulier, « er zijn » + pluriel. Variante orale : jeu de rôle client·e / marchand·e.',
      },
      {
        t: 'Mijn nieuwe collega', fr: 'Le nouveau collègue', mode: 'O',
        sit: 'Un·e nouveau·elle collègue arrive. Présentez-le ou présentez-la à l’équipe.',
        scene: [['bg', 'in', 'EAF2FB', 'EADFCF', 0.72], ['sign', 'WELKOM!', 0.33, 0.06, 0.34, 0.13, 'accent3'], ['e', 'man-office-worker', 0.04, 0.3, 0.52], ['e', 'woman-office-worker', 0.59, 0.3, 0.52],
          ['e', 'waving-hand', 0.43, 0.3, 0.17], ['e', 'potted-plant', 0.43, 0.6, 0.2]],
        crit: [
          { t: 'Donnez son nom et son pays avec **HEET** et **KOMT UIT**.', k: 'HEET / KOMT UIT' },
          { t: 'Donnez son âge avec **IS … JAAR**.', k: 'IS … JAAR' },
          { t: 'Présentez son métier avec **WERKT ALS** + profession.', k: 'WERKT ALS' },
          { t: 'Utilisez un possessif : **ZIJN** ou **HAAR**.', k: 'ZIJN / HAAR' },
          { t: 'Terminez par un détail amusant avec **GRAAG**.', k: 'GRAAG' },
        ],
        ex: [
          'Dit is onze nieuwe collega: hij {1:heet|HEET} Lucas en hij {1:komt uit|KOMT UIT} Frankrijk.',
          'Hij {2:is vijfendertig jaar} oud.',
          'Hij {3:werkt als} boekhouder in ons team.',
          '{4:Zijn|ZIJN} vrouw is Belgisch en {4:zijn|ZIJN} kinderen spreken Nederlands.',
          'En hij danst {5:graag} salsa… op kantoor!',
        ],
        notes: 'La 3e personne exige le -t (heet, komt, werkt, danst). « zijn » est ici le possessif (son, sa, ses) et non le verbe « être » : profitez-en pour distinguer les deux. Variante : présenter un·e camarade de classe après une mini-interview.',
      },
      {
        t: 'Mijn huis', fr: 'Mon logement', mode: 'W',
        sit: 'Vous avez un nouvel appartement. Décrivez-le à un·e ami·e par message.',
        scene: [['bg', 'in', 'FDF1E6', 'EADFCF', 0.72], ['win', 0.6, 0.1, 0.3, 0.4], ['e', 'sun-behind-cloud', 0.68, 0.15, 0.14], ['e', 'framed-picture', 0.14, 0.08, 0.2],
          ['e', 'couch-and-lamp', 0.04, 0.34, 0.46], ['e', 'potted-plant', 0.8, 0.48, 0.25], ['e', 'key', 0.5, 0.68, 0.15]],
        crit: [
          { t: 'Dites où vous habitez avec **WONEN** + **IN** + ville.', k: 'WONEN IN' },
          { t: 'Donnez le nombre de pièces avec **HEBBEN** + nombre.', k: 'HEEFT + nombre' },
          { t: 'Décrivez avec deux adjectifs : un **qualificatif** (+ -E) et un **attribut**.', k: 'QUALIFICATIF / ATTRIBUT' },
          { t: 'Situez un meuble avec **NAAST**, **ONDER**, **OP** ou **IN**.', k: 'PRÉPOSITION' },
          { t: 'Terminez par une chute avec **MAAR**.', k: 'MAAR' },
        ],
        ex: [
          'Ik {1:woon nu in} Leuven, vlak bij het station.',
          'Mijn appartement {2:heeft twee} slaapkamers en een balkon.',
          'Ik heb een {3:grote|QUALIFICATIF + -E} keuken en de woonkamer {3:is gezellig|ATTRIBUT}.',
          'De bank staat {4:naast} het raam.',
          '{5:Maar} er is geen lift… en ik woon op de vijfde verdieping!',
        ],
        notes: 'Qualificatif = devant le nom, avec -e (een grote keuken) ; attribut = après « zijn », sans -e (de woonkamer is gezellig). Attention : « een groot huis » (het-woord, indéfini) n’a pas de -e. « de bank » = le canapé (et la banque).',
      },
      {
        t: 'Een familiefoto', fr: 'Une photo de famille', mode: 'O',
        sit: 'Montrez une photo de famille (réelle ou imaginaire) et présentez-la.',
        scene: [['bg', 'in', 'FBEAF2', 'EADFCF', 0.8], ['r', 0.17, 0.06, 0.66, 0.66, 'B8865B', 0.02], ['r', 0.2, 0.1, 0.6, 0.58, 'FFFFFF', 0], ['r', 0.2, 0.48, 0.6, 0.2, 'D5E8D4', 0],
          ['e', 'man', 0.22, 0.18, 0.34], ['e', 'woman', 0.38, 0.16, 0.34], ['e', 'boy', 0.54, 0.3, 0.26], ['e', 'dog-face', 0.67, 0.42, 0.18], ['e', 'camera-with-flash', 0.02, 0.66, 0.28]],
        crit: [
          { t: 'Commencez par **OP DEZE FOTO** + verbe + sujet (inversion).', k: 'OP DEZE FOTO' },
          { t: 'Présentez deux personnes avec **MIJN** + un membre de la famille.', k: 'MIJN + famille' },
          { t: 'Décrivez quelqu’un avec **HEEFT** + adjectif + nom (cheveux, yeux…).', k: 'HEEFT + adj. + nom' },
          { t: 'Situez deux personnes avec **LINKS**, **RECHTS** ou **NAAST**.', k: 'LINKS / RECHTS / NAAST' },
          { t: 'Terminez par une chute avec **NIET**.', k: 'NIET' },
        ],
        ex: [
          '{1:Op deze foto zie je} mijn familie op vakantie.',
          'Dat is {2:mijn moeder} en dat is {2:mijn broer} Tom.',
          'Tom {3:heeft lang haar} en blauwe ogen.',
          'Mijn vader staat {4:links|LINKS}, {4:naast|NAAST} de hond.',
          'En de man rechts? Ik ken hem {5:niet}!',
        ],
        notes: '« lang haar » sans -e (het haar, indéfini) mais « blauwe ogen » avec -e (pluriel) : bonne occasion de revoir la règle. « niet » se place ici en fin de phrase (ik ken hem niet). Variante : les apprenant·es montrent une vraie photo sur leur téléphone.',
      },
      {
        t: 'Mijn dag', fr: 'Ma journée', mode: 'W',
        sit: 'Décrivez une journée de travail ordinaire, du matin au soir.',
        scene: [['bg', 'out', 'FDF1E6', 'FDF1E6', 1], ['line', 0.06, 0.62, 0.94, 0.62, 'D5DCE6'], ['e', 'sun', 0.04, 0.04, 0.16], ['e', 'crescent-moon', 0.84, 0.04, 0.16],
          ['e', 'alarm-clock', 0.04, 0.38, 0.2], ['e', 'hot-beverage', 0.23, 0.38, 0.2], ['e', 'train', 0.42, 0.38, 0.2], ['e', 'laptop', 0.61, 0.38, 0.2], ['e', 'cooking', 0.8, 0.38, 0.2],
          ['sign', '7:00', 0.05, 0.7, 0.13, 0.11, 'accent1'], ['sign', '7:15', 0.24, 0.7, 0.13, 0.11, 'accent1'], ['sign', '8:00', 0.43, 0.7, 0.13, 0.11, 'accent1'], ['sign', '9:00', 0.62, 0.7, 0.13, 0.11, 'accent1'], ['sign', '19:00', 0.81, 0.7, 0.14, 0.11, 'accent1']],
        crit: [
          { t: 'Commencez par l’heure : **OM … UUR** + verbe + sujet (inversion).', k: 'OM … UUR' },
          { t: 'Dites comment vous allez au travail avec **MET DE** + transport.', k: 'MET DE + transport' },
          { t: 'Utilisez un verbe à particule (**OPBELLEN**, **OPSTAAN**…) : la particule va à la fin.', k: 'PARTICULE' },
          { t: 'Enchaînez avec **EERST** et **DAN** (inversion !).', k: 'EERST / DAN' },
          { t: 'Terminez par votre soirée avec **’S AVONDS** + une chute.', k: '’S AVONDS' },
        ],
        ex: [
          '{1:Om zeven uur drink ik} een grote koffie.',
          'Ik ga {2:met de trein} naar mijn werk.',
          'Op kantoor {3:bel|BEL…} ik veel klanten {3:op|…OP}.',
          '{4:Eerst lees ik|EERST + inversion} mijn mails, {4:dan heb ik|DAN + inversion} een vergadering.',
          '{5:’s Avonds kook ik}… of ik bestel een pizza!',
        ],
        notes: 'Faites repérer les deux morceaux du verbe à particule : « ik bel… op » (opbellen). Inversion après un complément de temps en tête : om zeven uur drink ik, eerst lees ik, ’s avonds kook ik. « met de trein / met de bus / met de fiets », mais « te voet » (à pied).',
      },
      {
        t: 'Het weer en mijn kleren', fr: 'La météo et mes vêtements', mode: 'W',
        sit: 'Regardez la météo. Écrivez à un·e ami·e ce que vous mettez aujourd’hui.',
        scene: [['bg', 'out', 'DCE3EA', 'D5E8D4', 0.72], ['e', 'cloud-with-rain', 0.05, 0.03, 0.3], ['e', 'cloud-with-rain', 0.55, 0.0, 0.24], ['e', 'wind-face', 0.8, 0.05, 0.2],
          ['e', 'umbrella-with-rain-drops', 0.36, 0.3, 0.38], ['e', 'coat', 0.04, 0.48, 0.28], ['e', 'scarf', 0.64, 0.56, 0.2], ['sign', '8 °C', 0.8, 0.5, 0.17, 0.14, 'accent2']],
        crit: [
          { t: 'Décrivez le temps avec des verbes météo : **HET REGENT**, **HET WAAIT**…', k: 'HET REGENT…' },
          { t: 'Donnez la température avec **HET IS … GRADEN**.', k: '… GRADEN' },
          { t: 'Utilisez **IK DRAAG** + un vêtement et une couleur.', k: 'DRAAG + couleur' },
          { t: 'Justifiez avec **WANT**.', k: 'WANT' },
          { t: 'Terminez par une chute avec **MORGEN GA IK** + infinitif.', k: 'GA + infinitif' },
        ],
        ex: [
          'Vandaag {1:regent het|HET REGENT} en {1:het waait|HET WAAIT} hard.',
          'Het is maar {2:acht graden}.',
          'Ik {3:draag|DRAAG} een {3:gele|couleur + -E} regenjas en blauwe laarzen.',
          'Ik neem ook een paraplu, {4:want} ik wil niet nat worden.',
          '{5:Morgen ga ik|MORGEN GA IK} op een terras {5:zitten|+ infinitif}… in Spanje!',
        ],
        notes: 'Verbes météo impersonnels : het regent, het waait, het sneeuwt, de zon schijnt. « want » + ordre normal (want ik wil…). Futur proche : gaan + infinitif à la fin de la phrase. Variante orale : un bulletin météo présenté devant la classe.',
      },
      {
        t: 'Bij de dokter', fr: 'Chez le médecin', mode: 'O',
        sit: 'Vous êtes malade. Expliquez au médecin ce qui ne va pas.',
        scene: [['bg', 'in', 'E8F4EC', 'EADFCF', 0.75], ['sign', 'DOKTER', 0.04, 0.06, 0.3, 0.12, 'accent3'], ['e', 'man-health-worker', 0.58, 0.2, 0.56], ['e', 'face-with-thermometer', 0.08, 0.3, 0.36],
          ['e', 'stethoscope', 0.4, 0.58, 0.2], ['e', 'pill', 0.1, 0.74, 0.14]],
        crit: [
          { t: 'Saluez et dites comment vous allez avec **IK BEN** + adjectif.', k: 'IK BEN + adj.' },
          { t: 'Utilisez **IK HEB PIJN AAN** + une partie du corps.', k: 'PIJN AAN' },
          { t: 'Dites depuis quand avec **SINDS**.', k: 'SINDS' },
          { t: 'Posez une question avec **MOET IK** … + infinitif à la fin.', k: 'MOET IK … + inf.' },
          { t: 'Terminez par une chute avec **GEEN** ou **NIET**.', k: 'GEEN / NIET' },
        ],
        ex: [
          'Goedemorgen, dokter, {1:ik ben ziek} en heel moe.',
          'Ik heb {2:pijn aan} mijn hoofd en aan mijn keel.',
          'Ik hoest {3:sinds maandag}.',
          '{4:Moet ik|MOET IK} morgen {4:thuisblijven|+ infinitif}?',
          'Wat? Ik mag {5:geen} chocolade meer eten?!',
        ],
        notes: 'Jeu de rôle par deux (médecin / patient·e). Le médecin peut répondre avec « U moet rusten » ou « Neem deze siroop ». « sinds » + présent (ik hoest sinds maandag = je tousse depuis lundi). Variante : changer la partie du corps à chaque tour (buik, rug, oor…).',
      },
    ],
  },
  {
    id: 'A2', name: 'A2 · Survie', color: 'accent2',
    spec: ['**perfectum** (hebben / zijn)', 'imparfait **was / had / moest**', '**comparatif / superlatif**', 'diminutifs · impératif', 'verbes **pronominaux** · modaux · **zullen**', '**want · omdat · dus · daarom**', '**als / dat** + verbe à la fin', '**deze / die / dit / dat**', '**naar / tussen / boven**'],
    ctx: [
      {
        t: 'Een weekend aan zee', fr: 'Un week-end à la mer', mode: 'W',
        sit: 'Lundi matin : racontez votre week-end à la mer à un·e collègue, par message.',
        scene: [['bg', 'out', 'D6ECFA', 'F6E7C1', 0.62], ['r', 0, 0.5, 1, 0.12, '7FB3D5', 0], ['e', 'sun', 0.8, 0.03, 0.18], ['e', 'kite', 0.12, 0.02, 0.24], ['e', 'sailboat', 0.55, 0.33, 0.18],
          ['e', 'umbrella-on-ground', 0.02, 0.46, 0.4], ['e', 'shrimp', 0.42, 0.72, 0.16], ['e', 'automobile', 0.66, 0.72, 0.2], ['e', 'automobile', 0.82, 0.72, 0.2]],
        crit: [
          { t: 'Situez avec **VORIG WEEKEND** + un perfectum avec **ZIJN**.', k: 'ZIJN + participe' },
          { t: 'Utilisez deux verbes au perfectum avec **HEBBEN**.', k: 'HEBBEN + participe' },
          { t: 'Décrivez le temps à l’imparfait : **HET WAS** + adjectif.', k: 'HET WAS' },
          { t: 'Ajoutez une conséquence avec **DAAROM** (inversion !).', k: 'DAAROM + inversion' },
          { t: 'Terminez par une chute : un problème au retour, avec **MAAR**.', k: 'MAAR' },
        ],
        ex: [
          'Vorig weekend {1:ben|ZIJN} ik met vrienden naar Oostende {1:gegaan|+ participe}.',
          'We {2:hebben|HEBBEN} op het strand {2:gewandeld|+ participe} en veel garnalen {2:gegeten|+ participe}.',
          '{3:Het was} zonnig, maar er was veel wind.',
          '{4:Daarom hebben we} een vlieger gekocht.',
          '{5:Maar} op de terugweg hebben we drie uur in de file gestaan!',
        ],
        notes: 'Déplacement vers un lieu → zijn (ik ben naar Oostende gegaan) ; la plupart des autres verbes → hebben. Après « daarom », le verbe vient en 2e position (daarom hebben we…). « in de file staan » = être dans les bouchons. Faites souligner les participes (ge- … -d / -t / -en).',
      },
      {
        t: 'Mijn nieuwe appartement', fr: 'Mon nouvel appartement', mode: 'W',
        sit: 'Samedi soir, vous êtes enfin dans votre nouvel appartement. Décrivez l’ambiance.',
        scene: [['bg', 'in', 'FDF1E6', 'EADFCF', 0.74], ['win', 0.05, 0.1, 0.18, 0.36], ['win', 0.41, 0.1, 0.18, 0.36], ['r', 0.24, 0.52, 0.16, 0.03, 'B8865B', 0], ['e', 'desktop-computer', 0.26, 0.34, 0.17],
          ['e', 'mirror', 0.71, 0.06, 0.25], ['e', 'couch-and-lamp', 0.63, 0.38, 0.4], ['e', 'musical-notes', 0.88, 0.02, 0.12]],
        crit: [
          { t: 'Situez le contexte avec l’auxiliaire **ZIJN**.', k: 'ZIJN' },
          { t: 'Décrivez l’ambiance avec trois adjectifs : deux **qualificatifs** et un **attribut**.', k: 'QUALIFICATIF / ATTRIBUT' },
          { t: 'Utilisez au moins une préposition parmi **NAAR**, **TUSSEN** et **BOVEN**.', k: 'NAAR / TUSSEN / BOVEN' },
          { t: 'Utilisez **WANT** ou **OMDAT**.', k: 'WANT / OMDAT' },
          { t: 'Concluez par une chute finale de votre choix.', k: 'CHUTE' },
        ],
        ex: [
          'Het is zaterdagavond en ik {1:ben} eindelijk in mijn nieuwe appartement.',
          'Het is een {2:lichte|QUALIFICATIF}, {2:ruime|QUALIFICATIF} woonkamer en de sfeer {2:is gezellig|ATTRIBUT}.',
          'Mijn bureau staat {3:tussen|TUSSEN} de twee ramen en {3:boven|BOVEN} de bank hangt een spiegel.',
          'Ik ben heel blij, {4:omdat|OMDAT} ik nu dicht bij mijn werk {4:woon|verbe à la fin}.',
          '{5:Maar mijn buurman speelt elke avond om middernacht trompet!|CHUTE}',
        ],
        notes: 'Ce contexte reprend votre exemple de consigne. « want » + ordre normal (want ik woon nu…) ; « omdat » + verbe à la fin (omdat ik nu … woon). Qualificatifs avec -e devant le nom (een lichte, ruime woonkamer) ; attribut sans -e (de sfeer is gezellig). « boven de bank hangt… » : inversion après le complément de lieu.',
      },
      {
        t: 'Een feestje', fr: 'Une invitation', mode: 'W',
        sit: 'Vous organisez une fête d’anniversaire. Écrivez l’invitation à vos ami·es.',
        scene: [['bg', 'in', 'FBEAF2', 'EADFCF', 0.75], ['sign', '30!', 0.4, 0.06, 0.2, 0.17, 'accent4'], ['e', 'balloon', 0.05, 0.04, 0.26], ['e', 'balloon', 0.78, 0.04, 0.26],
          ['e', 'birthday-cake', 0.37, 0.4, 0.32], ['e', 'party-popper', 0.06, 0.5, 0.26], ['e', 'wrapped-gift', 0.72, 0.52, 0.24], ['e', 'top-hat', 0.6, 0.27, 0.16]],
        crit: [
          { t: 'Annoncez la fête avec un **diminutif** (-JE / -TJE).', k: 'DIMINUTIF' },
          { t: 'Donnez la date et l’heure avec **OP** … et **OM** …', k: 'OP … / OM …' },
          { t: 'Expliquez le chemin avec deux **impératifs** (NEEM, KOM, GA…).', k: 'IMPÉRATIF' },
          { t: 'Ajoutez une condition avec **ALS** (verbes à la fin).', k: 'ALS' },
          { t: 'Terminez par une consigne originale avec **MOETEN**.', k: 'MOETEN' },
        ],
        ex: [
          'Hallo allemaal, ik word dertig en ik geef een {1:feestje}!',
          'Het feest is {2:op zaterdag 12 oktober|OP + date} {2:om acht uur|OM + heure}.',
          '{3:Neem|IMPÉRATIF} tram 4 tot aan het park en {3:kom|IMPÉRATIF} dan naar nummer 15.',
          '{4:Als|ALS} je niet {4:kunt komen|verbes à la fin}, stuur me dan een berichtje.',
          'Opgelet: iedereen {5:moet|MOETEN} een hoed {5:dragen|+ infinitif}!',
        ],
        notes: 'Diminutifs : feest → feestje, bericht → berichtje, kaart → kaartje. Impératif = radical (neem, kom, ga) ; poli : « Neemt u… ». Avec « als », les verbes vont à la fin (als je niet kunt komen) et la principale commence par le verbe (stuur me dan…). Variante : l’invitation sous forme de message vocal.',
      },
      {
        t: 'De trein heeft vertraging', fr: 'Le train a du retard', mode: 'O',
        sit: 'Votre train est en retard. Laissez un message vocal à votre collègue.',
        scene: [['bg', 'out', 'D6ECFA', 'D5DCE6', 0.66], ['sign', 'NAMEN', 0.05, 0.06, 0.26, 0.12, 'accent2'], ['sign', '+ 40 MIN', 0.6, 0.06, 0.34, 0.14, 'accent6'],
          ['e', 'man-office-worker', 0.04, 0.32, 0.5], ['e', 'mobile-phone', 0.33, 0.5, 0.14], ['e', 'train', 0.58, 0.36, 0.3]],
        crit: [
          { t: 'Présentez-vous et dites où vous êtes avec **STAAN** ou **ZITTEN**.', k: 'STAAN / ZITTEN' },
          { t: 'Expliquez le problème au **perfectum**.', k: 'PERFECTUM' },
          { t: 'Annoncez votre arrivée avec **ZULLEN** + infinitif.', k: 'ZAL + infinitif' },
          { t: 'Demandez un service avec **KUN JE** … + infinitif ?', k: 'KUN JE … ?' },
          { t: 'Terminez par une excuse avec **SORRY DAT** (verbe à la fin) + une chute.', k: 'SORRY DAT' },
        ],
        ex: [
          'Hoi Sofie, met Karim: ik {1:sta} nog op het perron in Namen.',
          'Mijn trein {2:is|PERFECTUM} door een staking nog niet {2:vertrokken|+ participe}.',
          'Ik {3:zal|ZAL} pas om tien uur op kantoor {3:zijn|+ infinitif}.',
          '{4:Kun je|KUN JE} de vergadering een halfuurtje {4:uitstellen|+ infinitif}?',
          '{5:Sorry dat|SORRY DAT} ik weer te laat {5:ben|verbe à la fin}… voor de derde keer deze week!',
        ],
        notes: '« Met Karim » : formule du téléphone pour se présenter. Position : ik sta op het perron / ik zit in de trein. « vertrekken » fait son perfectum avec zijn (is vertrokken). Faites enregistrer le message sur le téléphone : c’est une vraie tâche orale. Variante : le ou la collègue rappelle et répond.',
      },
      {
        t: 'Een cadeau kopen', fr: 'Acheter un cadeau', mode: 'O',
        sit: 'Dans un magasin, vous cherchez un cadeau pour votre sœur. Comparez avec le vendeur ou la vendeuse.',
        scene: [['bg', 'in', 'F1ECF7', 'EADFCF', 0.74], ['r', 0.03, 0.43, 0.56, 0.03, 'B8865B', 0], ['e', 'scarf', 0.06, 0.2, 0.22], ['e', 'blue-book', 0.32, 0.22, 0.2],
          ['sign', '€ 80', 0.06, 0.5, 0.16, 0.1, 'accent6'], ['sign', '€ 20', 0.32, 0.5, 0.16, 0.1, 'accent3'], ['e', 'woman', 0.66, 0.14, 0.36], ['e', 'wrapped-gift', 0.7, 0.52, 0.24], ['e', 'shopping-bags', 0.05, 0.7, 0.24]],
        crit: [
          { t: 'Dites ce que vous cherchez avec **IK ZOEK** … **VOOR** …', k: 'IK ZOEK … VOOR' },
          { t: 'Comparez deux objets avec un **comparatif** + **DAN**.', k: 'COMPARATIF + DAN' },
          { t: 'Utilisez un **superlatif** (DE / HET … -STE).', k: 'SUPERLATIF' },
          { t: 'Montrez les objets avec **DEZE**, **DIE**, **DIT** ou **DAT**.', k: 'DEZE / DIE / DIT / DAT' },
          { t: 'Concluez avec **DUS** + une chute.', k: 'DUS' },
        ],
        ex: [
          'Goedendag, ik {1:zoek een cadeau voor} mijn zus.',
          'Het boek is {2:goedkoper dan} de sjaal.',
          'Maar de rode sjaal is {3:de mooiste} van de winkel.',
          'Mag ik {4:die|DIE} sjaal daar en {4:dit|DIT} boek eens zien?',
          'De sjaal kost tachtig euro, {5:dus} ik neem… het boek!',
        ],
        notes: 'Comparatif : adjectif + -er (+ dan) ; superlatif : de / het + adjectif + -st(e). Démonstratifs : deze / die avec les de-woorden, dit / dat avec les het-woorden ; deze / dit = près, die / dat = loin. Après « dus », les deux ordres sont possibles (dus ik neem / dus neem ik). Jeu de rôle client·e / vendeur·se.',
      },
      {
        t: 'Bij de apotheek', fr: 'À la pharmacie', mode: 'O',
        sit: 'Vous avez attrapé froid. Demandez conseil au pharmacien ou à la pharmacienne.',
        scene: [['bg', 'in', 'E8F4EC', 'EADFCF', 0.74], ['sign', 'APOTHEEK', 0.54, 0.05, 0.42, 0.12, 'accent3'], ['e', 'woman-health-worker', 0.62, 0.2, 0.46], ['r', 0.5, 0.6, 0.5, 0.4, '3E9A62', 0],
          ['e', 'pill', 0.52, 0.47, 0.13], ['e', 'honey-pot', 0.89, 0.46, 0.14], ['e', 'sneezing-face', 0.06, 0.28, 0.4]],
        crit: [
          { t: 'Dites depuis combien de temps avec **AL** + durée (+ présent).', k: 'AL + durée' },
          { t: 'Utilisez un verbe pronominal (**ZICH VOELEN**…).', k: 'PRONOMINAL' },
          { t: 'Demandez un conseil poliment avec **KUNT U** … + infinitif ?', k: 'KUNT U … ?' },
          { t: 'Posez une question avec **MOETEN** ou **MOGEN** + infinitif.', k: 'MOETEN / MOGEN' },
          { t: 'Terminez par une chute avec **TOCH**.', k: 'TOCH' },
        ],
        ex: [
          'Goedemiddag, ik hoest {1:al drie dagen}.',
          'Ik {2:voel me} niet goed en ik slaap slecht.',
          '{3:Kunt u|KUNT U} mij iets {3:aanraden|+ infinitif} voor de keel?',
          '{4:Moet|MOETEN} ik deze siroop voor of na het eten {4:nemen|+ infinitif}?',
          'Siroop met honing? Dan neem ik {5:toch} liever warme chocolademelk!',
        ],
        notes: '« al drie dagen » + présent = depuis trois jours (et ça continue). Pronominal : ik voel me, je voelt je, hij voelt zich. Registre poli : « u » avec le ou la pharmacien·ne. Variante : la personne à la pharmacie donne trois conseils à l’impératif (neem…, drink…, blijf…).',
      },
      {
        t: 'Een vakantiekaartje', fr: 'Une carte postale', mode: 'W',
        sit: 'Vous êtes en vacances. Écrivez une carte postale à vos collègues.',
        scene: [['bg', 'out', 'D6ECFA', 'F6E7C1', 0.7], ['r', 0, 0.56, 1, 0.14, '7FB3D5', 0], ['e', 'classical-building', 0.04, 0.16, 0.4], ['e', 'sun', 0.8, 0.04, 0.18],
          ['e', 'sailboat', 0.5, 0.4, 0.18], ['e', 'postbox', 0.74, 0.5, 0.34], ['e', 'sunglasses', 0.34, 0.76, 0.14]],
        crit: [
          { t: 'Dites depuis quand vous êtes là avec **ZIJN** + **SINDS**.', k: 'SINDS' },
          { t: 'Racontez hier avec un verbe à particule au perfectum (**OP-GE-STAAN**).', k: 'PARTICULE + GE' },
          { t: 'Décrivez avec l’imparfait **WAS** et **HAD**.', k: 'WAS / HAD' },
          { t: 'Comparez avec la Belgique : **… -ER DAN IN BELGIË**.', k: 'COMPARATIF' },
          { t: 'Terminez par une chute et **GROETJES**.', k: 'CHUTE + GROETJES' },
        ],
        ex: [
          'Beste collega’s, ik ben {1:sinds zaterdag} op Kreta.',
          'Gisteren zijn we om zes uur {2:opgestaan} voor een wandeling in de bergen.',
          'Het eten {3:was|WAS} lekker en we {3:hadden|HAD} een prachtig uitzicht.',
          'Het is hier veel {4:warmer dan} in België!',
          'Tot maandag… {5:of misschien blijf ik hier!|CHUTE} {5:Groetjes|GROETJES}, Karim',
        ],
        notes: 'Participe des verbes à particule : ge- entre la particule et le radical (opstaan → opgestaan, aankomen → aangekomen). « was / had » : imparfait de zijn et hebben, très utile pour décrire. Après « misschien », inversion (misschien blijf ik hier). Variante : écrire une vraie carte et la lire à voix haute.',
      },
      {
        t: 'Mijn eerste werkdag', fr: 'Mon premier jour de travail', mode: 'O',
        sit: 'Racontez votre premier jour dans votre nouvelle entreprise à un·e ami·e.',
        scene: [['bg', 'in', 'EAF2FB', 'EADFCF', 0.74], ['e', 'woman-office-worker', 0.04, 0.26, 0.56], ['r', 0.42, 0.64, 0.54, 0.03, 'B8865B', 0], ['e', 'clipboard', 0.47, 0.44, 0.2],
          ['e', 'card-index-dividers', 0.6, 0.46, 0.18], ['e', 'hot-beverage', 0.8, 0.46, 0.17], ['e', 'red-question-mark', 0.8, 0.14, 0.2]],
        crit: [
          { t: 'Commencez par **GISTEREN** + perfectum (inversion !).', k: 'GISTEREN + inversion' },
          { t: 'Décrivez vos collègues avec un **qualificatif** (+ -E) et un **attribut**.', k: 'QUALIFICATIF / ATTRIBUT' },
          { t: 'Utilisez **MOEST** (imparfait de moeten) + infinitif.', k: 'MOEST + infinitif' },
          { t: 'Donnez votre avis avec **IK VIND DAT** … (verbe à la fin).', k: 'IK VIND DAT' },
          { t: 'Terminez par une chute avec **EIGENLIJK**.', k: 'EIGENLIJK' },
        ],
        ex: [
          '{1:Gisteren ben ik begonnen} bij een bank in Brussel.',
          'Mijn collega’s {2:zijn vriendelijk|ATTRIBUT} en mijn baas is een {2:rustige|QUALIFICATIF + -E} man.',
          'Ik {3:moest|MOEST} de hele dag formulieren {3:invullen|+ infinitif}.',
          'Ik {4:vind dat|VIND DAT} het werk interessant {4:is|verbe à la fin}.',
          '{5:Eigenlijk} weet ik nog niet waar de koffiemachine staat…',
        ],
        notes: '« beginnen » fait son perfectum avec zijn (ik ben begonnen). Imparfait des modaux : moest, kon, wilde / wou, mocht. Après « dat », le verbe va à la fin. « Eigenlijk » (en fait) en tête → inversion (eigenlijk weet ik…). Variante : la conversation au téléphone avec un·e ami·e curieux·se.',
      },
    ],
  },
  {
    id: 'B1', name: 'B1 · Seuil', color: 'accent4',
    spec: ['subordonnées : **toen, terwijl, nadat, hoewel, zodat, indien**', '**relatives** : die / dat / waar + préposition', '**passif** : worden, er wordt', 'conditionnel **zou(den)**', '**plus-que-parfait** · discours indirect', '**om … te** + infinitif', '**er** + préposition', 'connecteurs : **bovendien, enerzijds / anderzijds, echter, kortom**', 'registre **formel** (u, Geachte…)'],
    ctx: [
      {
        t: 'Een klacht', fr: 'Une réclamation', mode: 'W',
        sit: 'Votre colis est arrivé en retard et abîmé. Écrivez au service clients.',
        scene: [['bg', 'in', 'F1F3F6', 'EADFCF', 0.74], ['e', 'warning', 0.06, 0.06, 0.2], ['e', 'package', 0.06, 0.42, 0.34], ['e', 'collision', 0.27, 0.36, 0.18], ['e', 'laptop', 0.55, 0.4, 0.34],
          ['e', 'e-mail', 0.64, 0.07, 0.22], ['e', 'face-with-steam-from-nose', 0.86, 0.06, 0.16]],
        crit: [
          { t: 'Ouvrez avec **GEACHTE** … et situez votre commande au **perfectum**.', k: 'GEACHTE / PERFECTUM' },
          { t: 'Utilisez le **passif** au passé : **WERD** + participe.', k: 'WERD + participe' },
          { t: 'Utilisez une **relative** avec **DIE** ou **DAT** (verbe à la fin).', k: 'RELATIVE' },
          { t: 'Formulez votre demande au conditionnel : **ZOU** … **WILLEN**.', k: 'ZOU … WILLEN' },
          { t: 'Terminez fermement avec **INDIEN** + une formule finale.', k: 'INDIEN / FORMULE' },
        ],
        ex: [
          '{1:Geachte heer, mevrouw|GEACHTE}, op 3 maart {1:heb|PERFECTUM} ik een koffiezetapparaat bij u {1:besteld|+ participe}.',
          'Het pakket {2:werd|WERD} pas twee weken later {2:geleverd|+ participe}.',
          'Bovendien was het toestel {3:dat ik ontving|RELATIVE : verbe à la fin} beschadigd.',
          'Ik {4:zou|ZOU} dan ook graag een nieuw toestel {4:willen ontvangen|WILLEN + infinitif}.',
          '{5:Indien|INDIEN} ik binnen tien dagen niets van u {5:hoor|verbe à la fin}, vraag ik mijn geld terug. {5:Met vriendelijke groeten|FORMULE}, Karim Benali',
        ],
        notes: 'Registre formel : u / uw, « Geachte heer, mevrouw », « Met vriendelijke groeten ». Passif : worden + participe (werd geleverd = fut livré). « indien » = « als » formel, verbe à la fin ; la principale qui suit commence par le verbe (…, vraag ik). « dan ook » = par conséquent.',
      },
      {
        t: 'Het sollicitatiegesprek', fr: 'L’entretien d’embauche', mode: 'O',
        sit: 'Lors d’un entretien, présentez votre parcours et votre motivation.',
        scene: [['bg', 'in', 'EAF2FB', 'EADFCF', 0.74], ['e', 'man-office-worker', 0.04, 0.2, 0.5], ['e', 'woman-office-worker', 0.6, 0.2, 0.5], ['r', 0.04, 0.66, 0.92, 0.04, 'B8865B', 0],
          ['e', 'page-facing-up', 0.43, 0.48, 0.17], ['e', 'handshake', 0.42, 0.1, 0.19]],
        crit: [
          { t: 'Présentez votre parcours avec **NADAT** + plus-que-parfait.', k: 'NADAT + HAD' },
          { t: 'Utilisez une relative avec **WAAR**.', k: 'WAAR' },
          { t: 'Exprimez votre but avec **OM … TE** + infinitif.', k: 'OM … TE' },
          { t: 'Nuancez une faiblesse avec **HOEWEL**.', k: 'HOEWEL' },
          { t: 'Terminez par une question audacieuse au conditionnel : **ZOU IK** … ?', k: 'ZOU IK … ?' },
        ],
        ex: [
          '{1:Nadat|NADAT} ik mijn diploma {1:had behaald|HAD + participe}, heb ik vijf jaar als boekhouder gewerkt.',
          'Dat was bij een kleine firma {2:waar} ik veel heb geleerd.',
          'Ik solliciteer bij uw bedrijf {3:om|OM} nieuwe uitdagingen {3:aan te gaan|TE + infinitif}.',
          '{4:Hoewel|HOEWEL} ik nog geen ervaring als teamleider {4:heb|verbe à la fin}, werk ik graag samen.',
          '{5:Zou ik|ZOU IK} misschien ook vier dagen per week {5:mogen werken|+ infinitifs}?',
        ],
        notes: 'Plus-que-parfait : had / was + participe (nadat ik … had behaald). Verbe à particule : aan te gaan (te entre la particule et le verbe). Après une subordonnée en tête, la principale commence par le verbe (…, heb ik / …, werk ik). Jeu de rôle recruteur·euse / candidat·e, avec deux questions de relance.',
      },
      {
        t: 'Verhuisd!', fr: 'On a déménagé !', mode: 'W',
        sit: 'Vous avez déménagé. Racontez la journée du déménagement à un·e ami·e par e-mail.',
        scene: [['bg', 'out', 'D6ECFA', 'D5DCE6', 0.72], ['e', 'cloud-with-rain', 0.42, 0.0, 0.24], ['e', 'house', 0.03, 0.12, 0.5], ['e', 'delivery-truck', 0.56, 0.36, 0.4],
          ['e', 'package', 0.39, 0.58, 0.16], ['e', 'package', 0.42, 0.44, 0.15], ['e', 'hot-beverage', 0.04, 0.76, 0.16]],
        crit: [
          { t: 'Plantez le décor avec **TOEN** + imparfait (verbe à la fin).', k: 'TOEN + OVT' },
          { t: 'Racontez deux actions simultanées avec **TERWIJL**.', k: 'TERWIJL' },
          { t: 'Utilisez le **plus-que-parfait** (HAD / WAS + participe).', k: 'PLUS-QUE-PARFAIT' },
          { t: 'Utilisez **ER** + préposition (ERIN, EROP, ERMEE…).', k: 'ER + prép.' },
          { t: 'Terminez par une chute avec **GELUKKIG**.', k: 'GELUKKIG' },
        ],
        ex: [
          '{1:Toen|TOEN} de verhuiswagen om acht uur {1:aankwam|OVT, verbe à la fin}, regende het pijpenstelen.',
          '{2:Terwijl|TERWIJL} mijn broer de kasten {2:droeg|verbe à la fin}, maakte ik koffie voor iedereen.',
          'Ik {3:had|HAD} alles goed {3:ingepakt|+ participe}, maar één doos viel van de trap.',
          'Mijn mooiste borden zaten {4:erin}…',
          '{5:Gelukkig} was de koffiemachine nog heel: het belangrijkste!',
        ],
        notes: '« toen » + passé (un moment précis) ≠ « als » (présent, futur ou répétition). Après la subordonnée, la principale commence par le verbe (…, regende het). « erin » remplace « in de doos » (er + préposition). « het regent pijpenstelen » = il pleut des cordes.',
      },
      {
        t: 'Een fietsongeluk', fr: 'Un accident à vélo', mode: 'O',
        sit: 'Vous avez vu un accident. Racontez à la police ce qui s’est passé.',
        scene: [['bg', 'out', 'D6ECFA', '9AA5B4', 0.64], ['r', 0.04, 0.82, 0.14, 0.025, 'FFFFFF', 0], ['r', 0.3, 0.82, 0.14, 0.025, 'FFFFFF', 0], ['r', 0.56, 0.82, 0.14, 0.025, 'FFFFFF', 0], ['r', 0.82, 0.82, 0.14, 0.025, 'FFFFFF', 0],
          ['sign', 'BUS', 0.86, 0.06, 0.11, 0.1, 'accent2'], ['e', 'person-standing', 0.85, 0.18, 0.3], ['e', 'woman-biking', 0.06, 0.34, 0.36], ['e', 'collision', 0.38, 0.36, 0.2], ['e', 'delivery-truck', 0.5, 0.32, 0.38], ['e', 'ambulance', 0.06, 0.74, 0.22]],
        crit: [
          { t: 'Plantez le décor à l’imparfait (**OVT**) : STOND, FIETSTE…', k: 'OVT' },
          { t: 'Racontez l’événement avec **PLOTSELING** + inversion.', k: 'PLOTSELING + inversion' },
          { t: 'Utilisez le **passif** au passé : **WERD** + participe.', k: 'WERD + participe' },
          { t: 'Rapportez des paroles au discours indirect : **ZEI DAT** …', k: 'ZEI DAT' },
          { t: 'Terminez par une chute avec **TOCH**.', k: 'TOCH' },
        ],
        ex: [
          'Ik {1:stond|OVT} aan de bushalte en een jonge vrouw {1:fietste|OVT} op het fietspad.',
          '{2:Plotseling reed} een bestelwagen zonder te kijken de straat op.',
          'De vrouw viel en {3:werd|WERD} met de ambulance naar het ziekenhuis {3:gebracht|+ participe}.',
          'De chauffeur {4:zei dat|ZEI DAT} hij haar niet {4:had gezien|verbe à la fin}.',
          'Een week later zag ik haar {5:toch} weer fietsen… met een helm!',
        ],
        notes: 'OVT pour le décor (stond, fietste) et pour les événements d’un récit. Discours indirect : « ik heb haar niet gezien » → « hij zei dat hij haar niet had gezien ». « zonder te kijken » = sans regarder. Variante : un·e apprenant·e joue le policier ou la policière et pose des questions (Hoe laat? Waar precies?).',
      },
      {
        t: 'Thuiswerken: voor of tegen?', fr: 'Télétravail : pour ou contre ?', mode: 'O',
        sit: 'Votre entreprise veut supprimer le télétravail. Donnez votre avis en réunion.',
        scene: [['bg', 'in', 'F1F3F6', 'EADFCF', 0.74], ['e', 'house', 0.06, 0.06, 0.28], ['e', 'office-building', 0.74, 0.06, 0.28], ['e', 'balance-scale', 0.4, 0.03, 0.28],
          ['e', 'laptop', 0.36, 0.42, 0.3], ['e', 'cat', 0.72, 0.52, 0.26], ['e', 'hot-beverage', 0.12, 0.56, 0.16]],
        crit: [
          { t: 'Donnez votre avis avec **VOLGENS MIJ** + inversion.', k: 'VOLGENS MIJ' },
          { t: 'Pesez le pour et le contre avec **ENERZIJDS** … **ANDERZIJDS** …', k: 'ENERZIJDS / ANDERZIJDS' },
          { t: 'Ajoutez un argument avec **BOVENDIEN** (inversion !).', k: 'BOVENDIEN' },
          { t: 'Faites une proposition avec **ALS** … **ZOUDEN** …, **ZOU** …', k: 'ALS … ZOU' },
          { t: 'Concluez avec **KORTOM** + une chute.', k: 'KORTOM' },
        ],
        ex: [
          '{1:Volgens mij is} thuiswerken een grote stap vooruit.',
          '{2:Enerzijds|ENERZIJDS} verlies je geen tijd in de file, {2:anderzijds|ANDERZIJDS} zie je je collega’s minder.',
          '{3:Bovendien werken} veel mensen thuis rustiger en efficiënter.',
          '{4:Als|ALS} we twee dagen per week thuis {4:zouden werken|ZOUDEN + infinitif}, {4:zou|ZOU} iedereen tevreden zijn.',
          '{5:Kortom}: ik stem voor thuiswerken… en mijn kat ook!',
        ],
        notes: 'Connecteurs suivis d’une inversion : volgens mij, enerzijds, anderzijds, bovendien (verbe en 2e position). Hypothèse : als + zou(den) …, zou + infinitif (on peut aussi dire : als we … werkten, zou…). Variante : débat en deux équipes, chaque phrase dite par un·e membre différent·e.',
      },
      {
        t: 'Een restaurantrecensie', fr: 'Un avis sur un restaurant', mode: 'W',
        sit: 'Vous avez dîné dans un nouveau restaurant. Écrivez un avis en ligne.',
        scene: [['bg', 'in', 'FDF1E6', 'EADFCF', 0.74], ['sign', 'DE LEPEL', 0.3, 0.05, 0.4, 0.13, 'tx2'], ['e', 'french-fries', 0.1, 0.4, 0.24], ['e', 'fork-and-knife-with-plate', 0.37, 0.34, 0.3],
          ['e', 'wine-glass', 0.72, 0.42, 0.2], ['e', 'hourglass-not-done', 0.86, 0.06, 0.16], ['e', 'star', 0.3, 0.8, 0.12], ['e', 'star', 0.39, 0.8, 0.12], ['e', 'star', 0.48, 0.8, 0.12], ['e', 'star', 0.57, 0.8, 0.12]],
        crit: [
          { t: 'Présentez le restaurant avec une **relative** (DIE / DAT, verbe à la fin).', k: 'RELATIVE' },
          { t: 'Décrivez le repas avec un **qualificatif** (+ -E) et un **superlatif**.', k: 'QUALIFICATIF / SUPERLATIF' },
          { t: 'Utilisez **WAAR** + préposition (WAAROP, WAARIN, WAARMEE…).', k: 'WAAR + prép.' },
          { t: 'Formulez une critique avec **ECHTER**.', k: 'ECHTER' },
          { t: 'Recommandez au conditionnel (**ZOU** … **AANRADEN**) + une chute.', k: 'ZOU … AANRADEN' },
        ],
        ex: [
          'Gisteren hebben we gegeten in De Lepel, een nieuw restaurant {1:dat vlak bij de Grote Markt ligt|RELATIVE : verbe à la fin}.',
          'De vis was heerlijk en de {2:huisgemaakte|QUALIFICATIF + -E} frietjes waren {2:de lekkerste|SUPERLATIF} van de stad.',
          'Het terras, {3:waarop} je tot laat in de zon kunt zitten, is een echte aanrader.',
          'De bediening was {4:echter} erg traag.',
          'Ik {5:zou|ZOU} het zeker {5:aanraden|AANRADEN}… als je niet te veel honger hebt!',
        ],
        notes: 'Relative : le verbe va à la fin (een restaurant dat … ligt). « waarop » = sur lequel (het terras waarop…) ; à l’oral, on entend aussi « waar je … op kunt zitten ». « echter » se place souvent après le verbe (de bediening was echter…). Variante : chaque apprenant·e donne une note de 1 à 5 étoiles et la justifie.',
      },
      {
        t: 'Duurzaam leven', fr: 'Vivre durablement', mode: 'O',
        sit: 'Votre commune lance un défi « zéro déchet ». Présentez vos bonnes résolutions en réunion de quartier.',
        scene: [['bg', 'out', 'D6ECFA', 'D5E8D4', 0.7], ['e', 'recycling-symbol', 0.05, 0.05, 0.22], ['e', 'globe-showing-europe-africa', 0.76, 0.04, 0.22], ['e', 'bicycle', 0.03, 0.48, 0.3],
          ['e', 'seedling', 0.4, 0.6, 0.18], ['e', 'cup-with-straw', 0.55, 0.46, 0.2], ['e', 'leafy-green', 0.7, 0.55, 0.2], ['e', 'toothbrush', 0.86, 0.6, 0.16]],
        crit: [
          { t: 'Dites ce qui a changé avec **SINDS** + présent (inversion).', k: 'SINDS + inversion' },
          { t: 'Expliquez un but avec **OM … TE** + infinitif.', k: 'OM … TE' },
          { t: 'Expliquez une conséquence avec **ZODAT** (verbe à la fin).', k: 'ZODAT' },
          { t: 'Donnez un conseil avec **ZOU(DEN)** … **MOETEN** + infinitif.', k: 'ZOU … MOETEN' },
          { t: 'Terminez par une chute avec **ZELFS**.', k: 'ZELFS' },
        ],
        ex: [
          '{1:Sinds een maand ga ik} met de fiets naar mijn werk.',
          'Ik neem een herbruikbare beker mee {2:om|OM} minder afval {2:te maken|TE + infinitif}.',
          'Ik koop mijn groenten op de markt, {3:zodat|ZODAT} ik geen plastic verpakkingen meer {3:heb|verbe à la fin}.',
          'Iedereen {4:zou|ZOU} minder vlees {4:moeten eten|MOETEN + infinitif}.',
          'Mijn buurman maakt {5:zelfs} zijn eigen tandpasta… maar die smaakt naar zeep!',
        ],
        notes: '« om … te » (but) : te + infinitif à la fin ; « zodat » (conséquence) + verbe à la fin. Conseil : je zou / u zou / iedereen zou … moeten + infinitif. Variante : chaque groupe prépare cinq résolutions et la classe vote pour la plus réaliste… et la plus folle.',
      },
      {
        t: 'Overlast van de buren', fr: 'Des voisins bruyants', mode: 'W',
        sit: 'Vos voisins font la fête tous les soirs. Écrivez-leur un petit mot, poli mais clair.',
        scene: [['bg', 'in', 'E6EBF2', 'F1F3F6', 0.5], ['r', 0, 0.48, 1, 0.04, '8A96A8', 0], ['e', 'speaker-high-volume', 0.06, 0.12, 0.24], ['e', 'musical-notes', 0.28, 0.06, 0.2], ['e', 'woman-dancing', 0.46, 0.05, 0.4],
          ['e', 'party-popper', 0.74, 0.14, 0.24], ['e', 'bed', 0.05, 0.62, 0.32], ['e', 'sleepy-face', 0.44, 0.6, 0.28], ['e', 'alarm-clock', 0.74, 0.66, 0.24]],
        crit: [
          { t: 'Présentez-vous avec une relative : **DIE** (verbe à la fin).', k: 'DIE' },
          { t: 'Décrivez le problème avec le passif impersonnel : **ER WORDT** + participe.', k: 'ER WORDT + participe' },
          { t: 'Nuancez avec **IK BEGRIJP DAT** …, **MAAR** …', k: 'BEGRIJP DAT…, MAAR' },
          { t: 'Proposez une solution avec **ZOUDEN JULLIE** … **KUNNEN** … ?', k: 'ZOUDEN … KUNNEN' },
          { t: 'Terminez par une chute sympathique avec **MISSCHIEN** + inversion.', k: 'MISSCHIEN' },
        ],
        ex: [
          'Beste buren, ik ben Sofie, de vrouw {1:die|DIE} op de tweede verdieping {1:woont|verbe à la fin}.',
          'Elke avond {2:wordt er|ER WORDT} tot twee uur ’s nachts luide muziek {2:gespeeld|+ participe}.',
          'Ik {3:begrijp dat|BEGRIJP DAT} jullie graag feesten, {3:maar|MAAR} ik moet om zes uur opstaan.',
          '{4:Zouden jullie|ZOUDEN JULLIE} de muziek na elf uur wat zachter {4:kunnen zetten|KUNNEN + infinitif}?',
          '{5:Misschien kunnen we} eens samen een feestje geven… om tien uur!',
        ],
        notes: 'Passif impersonnel : er wordt (veel) gefeest / muziek gespeeld (on fait la fête / on joue de la musique). Politesse : « Zouden jullie … kunnen … ? » est plus doux que « Kunnen jullie… ? ». « luide muziek » : qualificatif + -e. Variante : les voisin·es répondent par un petit mot.',
      },
    ],
  },
];

module.exports = { LEVELS };
